version: '3.8'

networks:
  my-network:
services:
  cleaner:
    build: .
    volumes:
      - ./dfs:/dfs
    entrypoint: ["node", "server.js"] 

  namenode:
    build: ./name-node
    depends_on:
      - cleaner
    ports:
      - "4000:4000"
    networks:
      - my-network
    volumes:
      - ./dfs:/dfs
    command: node nameNode.js
  crawler:
    build: ./crawler
    depends_on:
      - namenode
    networks:
      - my-network
    volumes:
      - ./dfs:/dfs
    command: node crawler.js

  map:
    build: ./map-node
    depends_on:
      - crawler
    networks:
      - my-network
    volumes:
      - ./dfs:/dfs
    command: sh -c "
      echo 'Waiting for split files...';
      while [ ! -f /dfs/split1.txt ] || [ ! -s /dfs/split1.txt ] ||
          [ ! -f /dfs/split2.txt ] || [ ! -s /dfs/split2.txt ]; do
      sleep 2;
      echo 'Still waiting for split files...';
      done;
      echo 'Split files found, starting processing...';
      node mapNode.js"

  reduce:
    build: ./reduce-node
    depends_on:
      - map
    volumes:
      - ./dfs:/dfs
    command: sh -c "
      echo 'Waiting for map outputs...';
      while [ ! -f /dfs/map-split1.txt ] || [ ! -f /dfs/map-split2.txt ]; do
        sleep 2;
        echo 'Waiting for map-split1.txt and map-split2.txt...';
      done;
      echo 'Map outputs found, starting reduce...';
      node reduceNode.js"

  search:
    build: ./search-api
    depends_on:
      - reduce
    ports:
      - "3000:3000"
    volumes:
      - ./dfs:/dfs
    command: sh -c "
      echo 'Waiting for index.json...';
      while [ ! -f /dfs/index.json ]; do
        sleep 2;
        echo 'Still waiting for index.json...';
      done;
      echo 'Index found, starting search API...';
      node searchApi.js"